### ISSUE TITLE
Database 다이어그램 수정본 및 변경 사항 (20.08.23)

### ISSUE THREAD

**Issue by kimdg1105** [Bletcher-Project/bletcher-back#23]
### ERD cloud 주소
link: www.erdcloud.com/d/joC6wdkB56mdsEJ3x

---- 
### 다이어그램 수정본
![db200823](https://user-images.githubusercontent.com/22341374/90977833-b21ddf00-e583-11ea-9059-10683b7a114c.png)
[db200823.pdf](https://github.com/Bletcher-Project/bletcher-back/files/5113895/db200823.pdf)

---- 
### 변경 사항
 - image table의 width, height 속성 삭제 및 path 속성 추가

**Comment by Seogeurim** [comment]
#24, #30 post에서 deleted_at(paranoid) 삭제하였습니다.
