### ISSUE TITLE
Cloudinary를 통한 Storage Upload

### ISSUE THREAD

**Issue by KimKwon** [Bletcher-Project/bletcher-back#27]
# Storage Upload via Cloudinary

## Cloudinary Info
![original](https://user-images.githubusercontent.com/22493971/91290600-c30e6080-e7ce-11ea-9e7e-8bc4430269d3.png)
Heroku의 Add-on이며 Cloudinary Docs에는 
Images made simple - uploads, storage, manipulations, optimizations, delivery 라고 소개하고 있다.

말 그대로, 이미지를 요리조리 쉽게 요리할 수 있게 해준다는 것 같다.

### 왜 Cloudinary인가? 
> 원래는 AWS S3를 사용하려고 했는데, 아마존에 전화까지해서 요청했지만 내 계정이 user activation이 너무 늦어져서....
> + 글을 작성하는 지금에서야 activate 됐다. 한 발 늦었다. 이미 다 구현했어.
> + Cloudinary와 S3의 compare하는 글을 많이 찾아봤는데 당장은 뭐가 더 낫다고 확실히 말을 못하겠다.
> + 당장은 Cloudinary를 사용하는 걸로.

## Cloudinary Usage
우선 express의 multer와 연동하여 쉽게 사용할 수 있도록 도와주는 모듈이 있다.
**multer-storage-cloudinary**이고 
``` yarn add multer-storage-cloudinary``` 로 install 가능하다.
> package.json에 있으니 알아서 잘 하시면 된다.

```javascript
// npm multer-storage-cloudinary package page
const storage = new CloudinaryStorage({
  cloudinary: cloudinary,
  params: {
    folder: 'some-folder-name',
    format: async (req, file) => 'png', // supports promises as well
    public_id: (req, file) => 'computed-filename-using-request',
  },
});
 
const parser = multer({ storage: storage });
 
app.post('/upload', parser.single('image'), function (req, res) {
  res.json(req.file);
});
```

기본적인 usage는 위와 같다.
CloudinaryStorage를 사용해서 생성한 스토리지 객체를 multer 미들웨어에게 넘겨주면 된다.
파일이 정상적으로 parse 되어 미들웨어를 거쳐왔다면, 라우터의 콜백함수에서 req.file로 접근이 가능하다.

---

위의 코드 중 마지막 3줄을 풀어서 말하자면
<font color='red'><i>/upload post요청의 이미지 파일이  multer 미들웨어를 거쳐 req 객체내의 file로써 정의되고, 
req.file로 접근이 가능하며 이를 response로 json화 해서 보내라~</i></font>
가 되겠다. 
> 개떡같이 말해도 찰떡같이 알아들을 것이라 믿으며....

### req.file
```javascript
// console.log(req.file);
{
  fieldname: 'img',
  originalname: 'original.png',
  encoding: '7bit',
  mimetype: 'image/png',
  path: 'https://res.cloudinary.com/cloudname/image/upload/something/post/15984401138775137781501.png',
  size: 3539,
  filename: 'post/15984401138775137781501'
}
```
req.file에는 내가 업로드한 파일에 대한 정보가 이러한 형식으로 담긴다.
데이터베이스 image 테이블의 path 속성값에 위의 path value 값을 주면... 아! 느낌이 오지 않는가? 🤷🏻‍♂️

---

CloudinaryStorage 객체가 Cloudinary에 저장될 파일의 정보를 나타낸다고 보면 된다.
 ### ColudinaryStroage.params
  1. params.folder : 실제 스토리지에 저장될 경로를 지정함. 해당 디렉토리명이 존재하지 않다면 생성함.
  2. params.format: 파일의 확장자를 의미함. 문자열로 제공하면 됨. 나는 원본 파일의 확장자를 추출하는 메소드를 작성해서 입력했음.
  3. params.public_id: 실제 스토리지에 저장될 파일의 이름을 지정함. 중복되면 overwrite되는 것으로 확인함. 
  Unique하게 지정하는 게 중요할듯 싶음. 그래서 나는 Date value + 난수 10자리로 지정함.

---
## Cloudinary Configuration

Heroku에서 Cloudinary로 이동하면 다음과 같은 화면을 볼 수 있다.

<img width="608" alt="스크린샷 2020-08-26 오후 7 49 33" src="https://user-images.githubusercontent.com/22493971/91295027-606c9300-e7d5-11ea-98b2-1c10c534497f.png">

Cloud name, API Key, API Secret이 우리 코드에서 Cloudinary API를 사용하기 위해 필요한 정보들이다. 

```javascript
cloudinary.config({ 
      cloud_name: CLOUD_NAME, 
      api_key: API_KEY, 
      api_secret: API_SECRET,
    });
```
> 이 코드는 config/index.ts에 추가해놓았다.

위와 같이 Cloudinary의 configuration 정보를 입력할 수 있다.
난 저 각 value값들을 .env 파일에 작성해서 사용했다. 

<img width="242" alt="스크린샷 2020-08-26 오후 7 54 27" src="https://user-images.githubusercontent.com/22493971/91295473-1afc9580-e7d6-11ea-80a4-5d15d2e26b64.png">

기존 방식이 어떤지 몰라서 일단 이렇게 사용했음. 피드백 시 반영하겠습니다.

🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

그리고 아직 마스터에 머지된 상태가 아니라 서버 URL을 헤로쿠로 두고 테스트하면 아무런 변화가 없습니다!
프론트에서 .env 파일 로컬호스트로 수정하고, 데이터베이스 확인하면서 테스트하시면 되겠습니다.

🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

---

### Cloudinary API
> https://cloudinary.com/documentation/admin_api#protocol_and_authentication

---

about PR
## Description
헤로쿠를 통해 서는 파일 업로드가 제한되어, 헤로쿠 add-on인 Cloudinary를 사용한 Storage Upload를 구현함.

## Branch

feature/upload

## Progress

- [x] Cloudinary로 이미지 업로드
- [x] Cloudinary의 이미지의 path를 프론트에 전달
- [x] 이미지 이름을 Unique하게 하기 ( 별도의 함수 작성 )

**Comment by Seogeurim** [comment]
최고에요 ㅠㅠ 진짜 너무 행복하다요 👍🏻👍🏻

환경변수 설정 관련은 #25 이슈의 [환경변수 설정] 부분 참고하면 됩니당 !!
그리고 .env.example 업데이트 하면 될듯합니당 !

\+ 추가적으로 util 함수 린트 확인, .DS_Store gitignore 추가 등 확인하면 될 것 같습니당 !

**Comment by kimdg1105** [comment]
이미지 처리가 매우 간편해졌습니다! 👍👍

**Comment by jjsk109** [comment]
혹시 이미지 용량이 큰 건 어떻게 처리 하셨나요?
