### ISSUE TITLE
[BUG] Heroku, Cloudinary and CORS Issue

### ISSUE THREAD

**Issue by KimKwon** [Bletcher-Project/bletcher-back#29]
## Describe the bug

Cloudinary 코드 마스터 머지 후 헤로쿠 배포/테스트 간 CORS 이슈 발생

### Screenshots

<img width="911" alt="스크린샷 2020-08-27 오후 4 25 11" src="https://user-images.githubusercontent.com/22493971/91410427-e3e3be00-e881-11ea-80e6-fb980be59d57.png">

### Additional context

> https://kamang-it.tistory.com/entry/Web%EB%8F%99%EC%9D%BC-%EC%B6%9C%EC%B2%98-%EC%A0%95%EC%B1%85-CORS-%EB%8F%84%EB%8C%80%EC%B2%B4-%EB%AD%98%EA%B9%8C

CORS에 대한 설명이 잘 돼있음.

## Branch

fix/cors

## To Do

- [ ] CORS 이슈발생 원인 찾기
- [ ] CORS 이슈 fix
- [ ] cloudinary config 구조 변경

**Comment by Seogeurim** [comment]
참고 자료 너무 좋네요 감사합니당 👍🏻🙌🏻
