### ISSUE TITLE
[REPORT] SameSite

### ISSUE THREAD

**Issue by KimKwon** [Bletcher-Project/bletcher-back#33]
> Bug 까지는 아닙니다 .... 하지만 중요하다고 생각해서 이슈로 정리하면서 작성합니다.
# 이 이슈는 다음의 Warning을 해결하기 위해 작성되었습니다.
<img width="241" alt="스크린샷 2020-08-27 오후 7 34 06" src="https://user-images.githubusercontent.com/22493971/91528135-0ccb8800-e942-11ea-9d7f-b065dadad120.png">

## First-Party Cookie and Third-Party Cookie
> Reference : https://web.dev/samesite-cookies-explained/

만약 너가 전에 보고 있던 사이트로 돌아갔다면, 넌 아마 단지 너가 현재 있는 사이트뿐 아니라 다양한 도메인의 쿠키가 있다는 걸 알 수 있을 것이다.
현재 사이트(주소창에 나와있는 그 놈)의 도메인과 일치하는 쿠키는 'first-party cookie' 라고 부른다.
비슷하게, 현재 사이트가 아닌 다른 도메인의 쿠키는 'third-party-cookie' 라고 부른다.
이건 절대적인 분류는 아니지만, 유저의 맥락? 흐름과 연관이 있다. 한 쿠키는 유저가 그 시간에 어떤 사이트에 있느냐에 따라 first-party 쿠키가 될 수도 third-party 쿠키가 될 수도 있는 것이다.

# SameSite

http response 헤더의 Set-Cookie의 속성 값 중 하나이다.

속성명에서 유추할 수 있듯이 도메인 간에 쿠키 생성/전송에 제약을 설정하는 속성 값이라고 생각하면 된다.

SameSite 에는 설정할 수 있는 3가지 String Value가 존재하는데, 간단히 설명만 하겠다.

1. **Strict**
  - 가장 제약이 강한 값이다.
  - first party 에서만 쿠키 전송이 가능하다. 즉, 다른 도메인에서는 쿠키 전송이 안됨.

2. **Lax**
  - Strict보다 조금 유한 값으로, Strict 설정에서 예외를 두는 방식이다.
  - HTTP/GET, a태그 href 등 SAFE한 method를 통해서만 쿠키 전송이 가능하다. 
  - 이 외에는 모두 Strict와 동일. 

3. **None**
  - 제약없이 쿠키 전송함.
  - Secure 속성을 반드시 정의해야함.

## Warning의 원인 (워닝의 원인) ㅋㅋ 

Warning 메시지를 읽어보면 
> 너는 Cloudinary에서 크로스사이트 데이터와 연관된 쿠키를 가져오고 있다. 근데 그 쿠키에 SameSite 속성 값이 정의 되어있지 않더라?
그래서 블락된거야. 현재 크롬에서는 SameSite: none 이랑 Secure을 같이 설정해야만 쿠키를 전송하고 있어. 그니까 SameSite 속성 좀 설정하고 다시해봐 ~~ 뭐 이런 뉘앙스다.

결과적으로, Cloudinary에서 받아오는 데이터의 쿠키가 우리 웹으로 왔는데, 그 쿠키에는 SameSite 속성이 정의되어있지 않고, 
우리 로컬에서 Cloudinary는 써드파티로 인식되기때문에 쿠키를 전송할 수 없다 뭐 이런 것 같다.

그럼 당연히 SameSite를 바꿔주면 되겠다.

---
### Express .cookie()

express에서 response header의 쿠키 값을 설정하는 API가 있다.
response.cookie() 로 접근 가능하고 usage는 다음과 같다.

```javascript
response
  .status(200)
  .cookie('same-site-cookie', 'http://cloudinary.com/', { sameSite: 'lax' })  .json(response.response200(COOKIE_SEND_SUCCESS, allPost));
```

적용 후 실행하면, 다음과 같이 확인 할 수 있다.
> 크롬 개발자 도구 -> 네트워크 -> posts -> reponse header

<img width="495" alt="스크린샷 2020-08-28 오후 4 05 48" src="https://user-images.githubusercontent.com/22493971/91531807-59b25d00-e948-11ea-9f7f-50826bc1f25f.png">

---

물론 이런 Warning이 뜬다고 무조건적으로 SameSite None 처박아~ 는 좋지 않은 행동이 될 수 있다.
CSRF(Cross-Site Request Fogery)나 의도치 않은 정보유출의 원인이 될 수도? 있지 않을까.

개발만 할 줄 알면 될 거라고 생각했는데, 진짜 알고 신경써야할 부분이 너무 많다.... 흑.

끝.

**Comment by kimdg1105** [comment]
오 깊게 생각해보지 않은 부분이네요.. SameSite 숙지하고 있겠습니당 👍

**Comment by Seogeurim** [comment]
우와.. 이런게 있구나 .. ㅠㅠ 흐아 너무 알아야 할 것들이 많구나.. ㅠㅠ 클라우디너리 설정하면서 많은 것들을 알아가네요 ㅠ 참고자료 한 번 읽어보면서 정리해봐야겠습니당 감사해요 👍🏻😊
