### ISSUE TITLE
Code Refactoring BACK

### ISSUE THREAD

**Issue by kimdg1105** [Bletcher-Project/bletcher-back#4]
# 코드 리팩토링을 하게 된 이유
 : 프로젝트를 진행 간 더 많은 개념들을 학습하면서 새로운 기능들이 추가되게 되었고, 이에 따라 전반적인 코드 리팩토링이 필요하게 되었다. 기존 코드의 clean-code화와 더불어 Database 스키마 수정 등 전반적 구조 재설계를 목표로 진행하고자 한다.

# 왜 지금인가?
 : 새로운 디자이너들과 개발자들의 합류로 인해 프로젝트에 더 박차를 가할 수 있는 시기라고 판단하여 진행하게 되었다.

### Node.js
 - [x] 1. node.js project architecture 재설계
 - [x] 2. Typescript 적용
 - [x] 3. Lint 적용
 - [x] 4. status code별 메시지 표준화
 - [x] 5. REST api 문서 관리
 - [x] 6. NST.py 코드 처리

### Database
 - [x] 1. Database 스키마 재설계
 - [x] 2. MariaDB 적용

### Others
 - [x] 1. README 작성

**Comment by Seogeurim** [comment]
## Typescript 적용

1. 현재 설치되어 있는 패키지 관련하여 필요한 Typescript 패키지 깔았습니다.

```json
 "dependencies": {
    "bcrypt": "^3.0.6",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "express": "~4.16.1",
    "jsonwebtoken": "^8.5.1",
    "mariadb": "^2.4.1",
    "method-override": "^3.0.0",
    "multer": "^1.4.2",
    "node-ssh": "^8.0.0",
    "sequelize": "^5.21.2",
    "ssh2-sftp-client": "^5.1.2",
    "winston": "^3.3.3"
  },
  "devDependencies": {
    "@types/bcrypt": "^3.0.0",
    "@types/bluebird": "^3.5.32",
    "@types/cors": "^2.8.6",
    "@types/express": "^4.17.7",
    "@types/jsonwebtoken": "^8.5.0",
    "@types/multer": "^1.4.3",
    "@types/node": "^14.0.23",
    "@types/validator": "^13.1.0",
    "nodemon": "^2.0.4",
    "ts-node": "^8.10.2",
    "typescript": "^3.9.7"
  }
```

2. tsconfig.json

```bash
npx tsc --init
```

하면 tsconfig.json 파일 생성되고 우리 프로젝트에 필요한 설정들 on 해주면 된답니당  
내가 설정한 것은

```js
{
  "compilerOptions": {
    /* Basic Options */
    "target": "ES6",
    "module": "commonjs",
    "allowJs": true,
    "sourceMap": true,
    "outDir": "./dist/",
    "rootDir": "./src",
    "removeComments": true,
    "preserveConstEnums": true,

    /* Strict Type-Checking Options */
    "strict": true,
    "noImplicitAny": true,

    /* Module Resolution Options */
    "moduleResolution": "node",

    /* Experimental Options */
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "include": ["./src/**/*"],
  "exclude": ["node_modules", "**/*.spec.ts"]
}

```

> tsconfig.json 설정 파일 관련 링크
> [컴파일러 옵션 (Compiler Options)](https://typescript-kr.github.io/pages/compiler-options.html)
> [tsconfig 컴파일 옵션 정리](https://vomvoru.github.io/blog/tsconfig-compiler-options-kr/)


## ESLint & Prettier 적용

> Bletcher FRONT 프로젝트에서 적용했던 린트 관련 이슈
> https://github.com/Bletcher-Project/bletcher-front/issues/9

프론트에 적용했던 것과 거의 동일하게 적용하였고, 대신 타입스크립트라서 [eslint-config-airbnb-typescript](https://www.npmjs.com/package/eslint-config-airbnb-typescript) 이거 **no React support** 버전으로다가 적용했습니당

`package.json` devDependencies

```json
    "@typescript-eslint/eslint-plugin": "^3.7.0",
    "@typescript-eslint/parser": "^3.7.0",
    "eslint": "^7.5.0",
    "eslint-config-airbnb-typescript": "^9.0.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-prettier": "^3.1.4",
    "prettier": "^2.0.5",
```

**Comment by Seogeurim** [comment]
### 특정 폴더에만 특정 eslint rule 끄고 싶을 때

model 정의할 때는 모델 간 관계 설정 때문에 모듈끼리 import를 할 수 밖에 없다. 모듈끼리 import를 하지만 서로의 모듈 기능을 사용하는 것이 아니고, 타입 선언을 위한 것이다. 하지만 삑 --- 린트 오류 ~~~~ eslint에서는 circular dependency 문제로 이것을 막아놨다. circular dependency가 고쳐지지 않으면 정말 많은 문제를 일으킬 수 있기 때문에 꼭 지켜야 하는 기본적인 속성이라고 한다.  
이 규칙 관련 도큐먼트는 다음 링크를 참조해보아랏 >>> [import/no-cycle](https://github.com/benmosher/eslint-plugin-import/blob/v2.22.0/docs/rules/no-cycle.md)

이 문제를 해결할 방법이 지금 당장은 떠오르지 않아서 models 폴더에만 이 규칙을 끄고 싶었다. 전체에 이 규칙을 꺼버리면 위험할 것 같아서 ㅠㅠ 그 방법은 다음과 같이 `.eslintrc` 파일에 overrides를 정의하는 것!!!

```js
{
  "extends": ["airbnb-typescript/base"],
  "parserOptions": {
    "project": "./tsconfig.json"
  },
  "overrides": [
    {
      "files": ["./src/models/*.ts"],
      "rules": {
        "import/no-cycle": 0
      }
    }
  ]
}
```

참고는 :: 난 스택오버플로우 없이 못 사는 병이 있지 >>> [ESLint ignore specific rule for a specific directory](https://stackoverflow.com/questions/41316551/eslint-ignore-specific-rule-for-a-specific-directory/41316801#41316801)

**Comment by Seogeurim** [comment]
> 5. REST api 문서 관리

[Bletcher Postman Dashboard](https://bletcher.postman.co/collections/10962716-0c35398a-8af6-4e70-bb2a-888e98c0e6c4?workspace=ffe62679-40a2-4cdf-89e0-e39f4a50eb93)
