### ISSUE TITLE
왜 MariaDB인가?

### ISSUE THREAD

**Issue by Seogeurim** [Bletcher-Project/bletcher-back#5]
초기 프로젝트 구상 시 관계형 데이터베이스 관리 시스템으로 MySQL을 선정했다. 
그러나 이번에 코드 리팩토링 이슈(#4)를 다루면서 MariaDB를 사용하자는 의견이 나왔다.
그렇다면, 우린 **왜 MariaDB인가?** 에 대한 이슈를 피할 수 없겠다는 생각을 했지. ㅎㅎㅎ

## MariaDB란?

가장 정확하다고 볼 수 있는 위키백과를 먼저 찾아갔다. [위키백과 - MariaDB](https://ko.wikipedia.org/wiki/MariaDB)
MariaDB는 핵심 개발자 몬티 와이드니어스의 둘째 딸 마리아 이름을 따서 지어진 것이라고 한다. 뭔가 가슴이 뭉클해져서.. 적어봤다 힣

MariaDB는 다음과 같은 특징들을 가지고 있다.

**1. MySQL과 동일한 소스 코드를 기반으로 한, 관계형 데이터베이스 관리 시스템(RDBMS)이다.**

MySQL과 동일한 소스 코드를 기반으로 하기 때문에 구조, 사용 방법, 명령어 등에 있어서 차이가 없다.
여기서 말하는 '차이가 없다'는 것은 구체적으로 다음과 같이 나타낼 수 있다.

> * 데이터와 테이블 정의 파일(.frm) 파일이 바이너리 호환이 된다.
> * 모든 클라이언트 API, 프로토콜 그리고 구조가 동일하다.
> * 모든 파일이름과 바이너리, 경로, 포트, 소켓 그리고 기타 등등이 동일하다.
> * 모든 MySQL 커넥터(PHP, Perl, 파이썬, 자바, .NET, MyODBC, Ruby, MySQL C 코넥터 등)가 마리아 DB와 동일하게 작동한다.

MariaDB의 기능들은 MySQL의 오픈소스 버전(~5.5)을 넘어 모든 버전을 대체할 수 있는 특징들을 갖추고 있다고 한다.

**2. 오픈 소스 (GPL v2 라이선스)**

MariaDB는 GPL v2 라이선스를 따르는 오픈소스이다. (여기 있지롱 ▶️ ▶️ https://github.com/MariaDB/server)

여기서 잠시 역사 시간이다. **MySQL AB**(MySQL 만든 회사)가 **썬 마이크로시스템즈**로 인수,  그리고 그 썬 마이크로시스템즈가 **오라클**에 인수되었다. 즉 MySQL은 오라클이 관리 및 지원하고 있다. MariaDB 개발자 몬티 와이드니어스는 다음과 같이 말했다고 한다.

> 아마도 InnoDB 스토리지 엔진을 제외한 MySQL에 있는 기능 대부분은 썬 마이크로시스템즈 때 있었던 기능들입니다. 오라클 인수 후 MySQL은 발전하지 않았습니다. 오라클은 ‘MySQL을 어떻게 하면 자신들의 소유로 할 수 있을까’만 고민했고, 그래서 회사를 나왔습니다.

MariaDB는 오픈소스 프로젝트이기에 오라클로부터 자유롭다. 누구나 필요로 하면 커뮤니티를 통해 마리아DB를 내려받아 쓸 수 있다.

**3. MySQL보다 좋은 성능**

MariaDB 커뮤니티는 다음과 같이 주장한다고 한다.

> MariaDB는 MySQL과 비교해 애플리케이션 부분 속도가 약 4~5천배 정도 빠르며, MySQL이 가지고 있는 모든 제품의 기능을 완벽히 구현하면서도 성능 면에서는 최고 70%의 향상을 보이고 있다.

**4. 기타 특징**

이 외의 특징들에 대해서는 너무 깊게 들어가는 느낌이라서 이런 특징이 있다~ 정도로만 알아두겠다.

* 새로운 저장 엔진 아리아(Aria), InnoDB를 교체할 수 있는 XtraDB 저장 엔진을 포함한다.
* 기존에 MySQL 엔터프라이즈에서 플러그인으로 제공한 쓰레드풀 기능이 내장되었다.
* 스토리지 엔진을 활용한 샤딩 기술을 제공한다. 

## 기업들은 MariaDB를 얼마나 많이 사용하고 있을까요?

오라클은 아무래도 비용이 있어서 큰 기업에서 많이 사용하지만, MariaDB는 그렇지 않아서 중소기업에서 많이 사용된다고 한다.
하지만 MariaDB가 가지고 있는 장점 때문에 구글, 위키피디아, 페이스북, 유튜브, 야후, 트위터, 링크드인, 아마존, 카카오톡 등의 세계적인 기업들도 MySQL에서 MariaDB로 전환이 많이 이루어지고 있다고 한다.

### 무슨 장점??

읽어보아라. [MariaDB+Brochure_Korean_2018ver.compressed.pdf](https://github.com/Bletcher-Project/bletcher-back/files/4912802/MariaDB%2BBrochure_Korean_2018ver.compressed.pdf)

## node.js에서 MariaDB 사용하기

- [node-mariasql](https://github.com/mscdex/node-mariasql) MariaDB의 논블로킹 운영을 수행하는 API
- [sequelize](https://github.com/sequelize/sequelize) PostgreSQL, MySQL, MariaDB, SQLite and MS-SQL을 지원하는 Node.js 기반의 ORM

우리 프로젝트에서 sequelize를 사용하고 있으니까 MariaDB를 설치해서 연결만 그 쪽으로 바꿔주면 될 것 같다.

## mac :: HomeBrew로 MariaDB 설치하기

그대로 설치하면 오류가 나더라. brew unlink mysql을 먼저 수행했어야 했다.

```bash
brew unlink mysql
brew install mariadb
```

![image](https://user-images.githubusercontent.com/22045163/87311550-56ab0b00-c55a-11ea-9041-5050f30eefe3.png)

![image](https://user-images.githubusercontent.com/22045163/87312052-0aac9600-c55b-11ea-997d-52cc32a8db7e.png)

> 흠... MySQL에 원래 있던 데이터베이스 목록 그대로 보여주네. 어떻게 이렇게 되지? 마리아디비 깔면 뭔가 기능은 마리아디비로 하고 뭐 원래 마이에스큐엘 쓰고 그런건가...? 대신 `MySQL [(none)]>` 이런 식으로 보여주긴 하네. 뒤에 갑자기 [(none)]이 붙었어. 이건 도대체 뭐지 ㅠㅠㅠㅠㅠ 으악

**Comment by kimdg1105** [comment]
모든 실용적인 목적에서 **MariaDB는 동일한 MySQL 버전을 즉시 교체할 수 있습니다**. (예를 들어 MySQL 5.1은 MariaDB 5.1, MariaDB 5.2, MariaDB 5.3과 호환되며, MySQL 5.5은 MariaDB 5.5와 호환된다.) 이는 다음과 같은 것을 의미합니다.

- **데이터와 테이블 정의 파일 (.frm) 파일들이 호환됩니다.**
- **모든 클라이언트 API, 프로토콜 및 구조가 동일합니다.**
- 모든 파일이름, 바이너리, 경로, 포트, 소켓이 모두 동일해야 한다
- 모든 MySQL 커넥터(PHP, Perl, Python, Java, .NET, MyODBC, Ruby, MySQL C connector 등)는 아무런 변화없이 MySQL에서 잘 작동합니다.
- 몇몇 PHP5에서의 설치 이슈가 존재한다. (오래된 PHP 클라이언트가 라이브러리 호환성을 검사하는 데서 발생하는 버그이다)
- 클라이언트 공유 라이브러리는 MySQL 클라이언트 라이브러리와 호환된다.
- **이는 대체로 MySQL을 삭제 한 뒤, MariaDB를 설치해도 잘 작동한다는 것을 의미합니다. (동일한 메인 버전에서는 데이터 파일을 변환할 필요없다.)**
참조: https://mariadb.com/kb/ko/mariadb-mysql/

MariaDB 공식 사이트에 나와있네요!
MySQL과 MariaDB 버전 간 호환성 문제도 있는 것 같으니 참조한 링크 한번 보세요!

**Comment by Seogeurim** [comment]
@kimdg1105 
호환이 되어서 그런거였군뇨 ㅠㅠ 감사해유
백 코드도 굳이 고칠 필요 없이 바로 MySQL 연동되서 돌아가더군뇨 
딱 알았웁니다 ><><
