### ISSUE TITLE
[BUG] PATCH /user route

### ISSUE THREAD

**Issue by Seogeurim** [Bletcher-Project/bletcher-back#51]
## Describe the bug

프로필 업데이트 프론트 작업 중 발견한 PATCH /user route 버그들을 정리해보았습니다.

### To Reproduce

1. checkPassword 체크 후 모든 정보를 수정하도록 하는데, 이미지는 그 과정 없이도 변경됩니다.
2. checkPassword 말고 비밀번호 자체를 변경하고자 하는 경우에 대한 처리가 없습니다.
3. checkPassword 체크 시 알맞지 않을 경우 400 코드를 주는데, 400을 주니 서버 통신 오류인지 다른 오류인지 헷갈립니다. 401/403 등으로 변경이 필요할 것 같습니다.
4. user 정보의 profile_image 필드가 이미지 url이 아닌 숫자 값으로 넘어오는데 어디서 바뀐 것인지 알아내야 할 것 같습니다.

## Branch

fix/users

## To Do

- [x] 프로필 이미지 업데이트 middleware : checkPassword 없이도 이미지는 변경되는 문제 처리
- [x] checkPassword 말고도 비밀번호를 변경하고자 하는 경우에 대한 처리
- [x] checkPassword 에러 코드 바꾸기
- [x] user 정보의 profile_image 필드를 어떻게 넘겨주는지 확인하고 이슈 해결

**Comment by kimdg1105** [comment]
와우,,, 확인해보고 수정하겠습니다 감사합니다!

**Comment by kimdg1105** [comment]
## To Do

- 프로필 이미지 업데이트 middleware : checkPassword 없이도 이미지는 변경되는 문제 처리
 : GET users/check 에서 기존 비밀번호 확인 후, 회원정보 변경으로 진행하는 것으로 해결

- checkPassword 말고도 비밀번호를 변경하고자 하는 경우에 대한 처리
 : PATCH 요청 BODY에 'password' 값을 통해 변경 (값이 들어오면 bcrypt 처리 후 정보 저장)

- checkPassword 에러 코드 바꾸기
 : 403으로 변경하였습니다! (401 : 토큰 없는 경우, 403: 토큰 있지만 체크 패스워드 다른 경우, modify에서 409 : 중복 이메일/닉네임)

- user 정보의 profile_image 필드를 어떻게 넘겨주는지 확인하고 이슈 해결
 : 이 부분은 User 테이블과 Image 테이블을 조인하고 getUser()에 대해 조인 값을 추가하여 해결하였습니다.
<img width="889" alt="스크린샷 2021-02-27 오후 5 43 26" src="https://user-images.githubusercontent.com/22341374/109382363-544bc480-7923-11eb-837f-70920f9ca678.png">
